project:
  type: website

website:
  title: "Mi Sitio en Quarto"
  navbar:
    left:
      - href: index.qmd
        text: "Página de Inicio"
      - text: "CAPÍTULO 1"
        menu:
          - href: CAPITULO_1/A1_intro_optimizacion.qmd
            text: "Introducción a la Optimización"
          - href: CAPITULO_1/A2_optimalidad.qmd
            text: "Condiciones de Optimalidad"
  page-navigation: true  # Activar navegación entre páginas

format:
  live-html:
    pyodide:
      cell-options:
        edit: true
        include: true
    css: style.css
    toc: true
    toc-depth: 3
    toc-location: left
    toc-floating: true
number-sections: true
lang: es
